### ISSUE TITLE
Can't turn autoplay off

### ISSUE THREAD

**Issue by ecruhling** [stamat/youtube-background#14]
No matter where I set it, I can't seem to get autoplay to set to 0. I know the script is just creating an autoplay parameter on the iframe URL, but no matter if I set it in JS or in the HTML, it is always autoplay=1

**Comment by webkubikc** [comment]
I agree stopping auto play doesn't work

**Comment by rasul-chopurov** [comment]
1.
go => **function YoutubeBackground(elem, params, id, uid) {**
and search => 	this.defaults = {
search  **'autoplay': true,** update => **'autoplay':false,**
search **'pause':false,** update=> **'pause':true,**
2 .
go => **YoutubeBackground.prototype.injectIFrame = function (**) 
and search => **var src = 'https://www.youtube.com/embed/'+this.ytid+'** 
and search **'?enablejsapi=1** update => **'?autoplay=0&enablejsapi=1

![+](https://user-images.githubusercontent.com/13812501/89824548-58b9b700-db64-11ea-856f-8f4d5d17ec32.png)
![2020-08-10_235037](https://user-images.githubusercontent.com/13812501/89824551-59eae400-db64-11ea-9ba3-81a378689182.png)

**

**Comment by stamat** [comment]
I've tested the `data-vbg-autoplay`, and the manual properties and I've confirmed this works. This is an old issue, so I can't be sure when I've fixed this issue.

This script was designed as a video background, so stopping the autoplay and the play functionalities were not initially intended, but added on request.
Anyway if the problem arises once again do let me know. ☺️
