### ISSUE TITLE
Can we play video with sound on by default ? 

### ISSUE THREAD

**Issue by sbenahmedNB** [stamat/youtube-background#19]
Can we play video with sound on by default ? 

Now when i load document (with original script) i have error : 
![image](https://user-images.githubusercontent.com/33460258/98107813-559c4180-1e9b-11eb-8c54-db254d48ab7a.png)

thank you for helping me

**Comment by sbenahmedNB** [comment]
Ok, i found : since 2018 we is not allowed to open player youtube autoplay with sound.

**Comment by stamat** [comment]
Yup, that's correct. It's annoying the visitors! Glad you found the info by yourself! Cheers! Happy Holidays!
