### ISSUE TITLE
youtube-background not covering the parent element / disable right mouse click popup

### ISSUE THREAD

**Issue by insad** [stamat/youtube-background#2]
youtube-background div was not covering the parent element; besides, right-mouse click on the background shows an ugly popup menu.
Solved it by adding some style to the injected youtube-background div:

                $root.css({
                    'height': '100%',
                    'width': '100%',
                    'z-index': 0,
                    'position': 'absolute',
                    'overflow': 'hidden',
                    'top': 0, // added
                    'left': 0,
                    'bottom': 0,
                    'right': 0,
                    'pointer-events': 'none' // avoid right mouse click popup menu
                });

**Comment by stamat** [comment]
@insad I'll see to it that these CSS properties are automatically added! Thanks dude!
