### ISSUE TITLE
Still try to load background image from YT ?

### ISSUE THREAD

**Issue by dotMastaz** [stamat/youtube-background#20]
Hi, 

First, very thank you to create this addon !!

In js, i add property "load-background" to false but try to still load the "maxresdefault.jpg" from YT ?
jQuery('#the-video[data-youtube]').youtube_background({'load-background': false});

An idea ?!

Thank you,
Nicolas

**Comment by apsolut** [comment]
Its old question but if anyone needs this, easy method is just to add data tag to <div> 
`<div 
data-ytbg-load-background="true" 
data-youtube="https://www.youtube.com/watch?v=eEpEeyqGlxA"></div>`

**Comment by stamat** [comment]
@apsolut jazz ba!? Hvala na odgovoru, toliko sam spor da je to užas... Pozz za tebe i divno Sarajevo ❤️ 

@dotMastaz you are welcome! Sorry for this extremely late reply...

**Comment by apsolut** [comment]
> @apsolut jazz ba!? Hvala na odgovoru, toliko sam spor da je to užas... Pozz za tebe i divno Sarajevo ❤️
> 
> @dotMastaz you are welcome! Sorry for this extremely late reply...

❤️ za BG, hvala za script btw

**Comment by stamat** [comment]
@apsolut nema na cemu bruda, valjda cu nekad imati vremena da sredim sve skripte hahaha!
