### ISSUE TITLE
Reduced motion query and accessibility

### ISSUE THREAD

**Issue by djmtype** [stamat/youtube-background#3]
Please respect and add support for the reduced motion query by adding an image fallback. Add a pause button. Respect motion sickness – please add a pause button

**Comment by stamat** [comment]
@djmtype thanks for the heads up! 

Now that you've mentioned it, these video covers are pretty annoying... I made these cause clients requested, but never actually gave a thought about them... 

How would that look interface wise? Any ideas or examples? I could make it pause on keyboard space or escape, or clicking on the surface... But then there should be a visual notice, like "Press escape to pause" or "Click to pause" which would not look great design wise. I wonder is there UX standard for this...

**Comment by stamat** [comment]
@djmtype alright, I believe I came up with a good solution in v1.0.3, please take a look.
