### ISSUE TITLE
Force HD quality? 

### ISSUE THREAD

**Issue by Aduffy** [stamat/youtube-background#38]
My video on YT is 1080 but when i embed it using this code the video looks to be a much lower resolution.. Is there a way to force it us use the highest quality available??

**Comment by stamat** [comment]
I'll take a look @Aduffy! And I'll tell you! Sorry for seeing this so late!

**Comment by stamat** [comment]
@Aduffy unfortunately it's not possible from Oct 24th 2019 :( https://developers.google.com/youtube/iframe_api_reference#october-24,-2019
