### ISSUE TITLE
Mute Properties

### ISSUE THREAD

**Issue by rodmar35** [stamat/youtube-background#4]
Hi,

Thanks for this repo.
Could you add a Mute true/false Properties ?
Thanks a lot.
RodMar

**Comment by stamat** [comment]
@rodmar35 will do!

**Comment by stamat** [comment]
Hey, I've added the option for muting and unmuting the video in the last version! I'm glad you like this script, thanks for using it!

**Comment by rodmar35** [comment]
Hi,

it works fine
Thanks a lot
RodMAr
