### ISSUE TITLE
Start-at and end-at won't work

### ISSUE THREAD

**Issue by adepani1** [stamat/youtube-background#40]
$(document).ready(function() {
        $('[data-vbg]').youtube_background({
            'start-at': 7,
            'end-at': 161,
            'load-background': true,

        });
});

**Comment by bantunesm** [comment]
Have you tried passing params directly in the tag ?
data-vbg-start-at="7"
data-vbg-end-at="161"

**Comment by stamat** [comment]
@adepani1 hey, sorry for the late reply! 

The code you've sent probably had some issues at the time you've sent it. I've reiterated the script in the past few days and refactored and fixed (hopefully) all of the issues. Do try the latest version **v1.1.0** ☺️ 

So I can confirm that `end-at` and `start-at` properties now work as intended, and in the case of your code they will set the start and end time of all of your video background.

To set the start and end times for individual background instances, you canuse the attributes that @bantunesm suggested. Thanks @bantunesm for replying to this issue!

Cheers! ✨
