### ISSUE TITLE
Youtube player gets injected even if there is no youtube or video

### ISSUE THREAD

**Issue by WHITE-developer** [stamat/youtube-background#43]
The youtube player api gets injected even when there is no `data-vbg` on the page.
Also gets injected when the `data-vbg` has a vimeo link.

**Comment by BoufouN** [comment]
Same issue here.

Can the package check if the YouTube API is needed before creating the youtube api script element?
[/src/youtube-background.js:6](https://github.com/stamat/youtube-background/blob/master/src/youtube-background.js#L6)

The player_api in it's turn loads another 164kB(!) file: [www-widgetapi.js](https://www.youtube.com/s/player/b50b69c9/www-widgetapi.vflset/www-widgetapi.js). It would result in a huge performance boost when it's only loaded when needed.

Proposed fix:
Load it once new `YoutubeBackground()` is called, except for when the script tag already exists.

**Comment by stamat** [comment]
This was mainly designed as a youtube background script lol, this is why it was always loading the api. Anyway you are absolutely right, the update is in the **v1.0.18**. Though now we carry the vimeo script with the code, lol, I'll see this updated in the next version!
