### ISSUE TITLE
Please provide some troubleshooting tips

### ISSUE THREAD

**Issue by adam-jones-net** [stamat/youtube-background#44]
Hi I request this generally as I think something in the readme about this would be really useful.   

My request comes because I am indeed having problems getting the code to work.  No JS errors.   It's definitely being called but it just doesn't insert the player into the DOM.     A search of the DOM with the browser dev tools confirms that.    It's also the same, irrelevant if I specify a YouTube or Vimeo url.  I also have no custom options defined.

Any general ideas on where to go to troubleshoot?

**Comment by EvanOlsen** [comment]
@adam-jones-net Are you pointing to the CDN? The CDN link is incorrect. As pointed out by another user here, https://github.com/stamat/youtube-background/issues/41, the CDN link should be: https://unpkg.com/youtube-background@1.0.14/jquery.youtube-background.js

I found it was best to just download the source files and incorporate the js into my build.
