### ISSUE TITLE
this.player.getvideodata is not a function 

### ISSUE THREAD

**Issue by jxnx888** [stamat/youtube-background#45]
I had this issue reported all the time. And I know Youtube API has removed the function already. How do I make this error go?

![image](https://user-images.githubusercontent.com/22604980/182938105-ec2b0463-f672-41fd-a33b-6c0cce8011ee.png)

**Comment by stamat** [comment]
@jxnx888 Seems like this is not a part of this codebase? Anyway you can always weap a piece of your code with `try/catch`! ☺️
