### ISSUE TITLE
Embedded YT playback quality poor on iOS Safari

### ISSUE THREAD

**Issue by simonfrost** [stamat/youtube-background#48]
Wondering if there's anything I can do to improve the quality of the embedded YT stream when viewing on iOS Safari.

Same page viewed on a desktop (reasonably recent Macbook / Chrome) looks to be playing HD (in whatever capacity) but the same page on the same local wifi connection viewed on iOS Safari is horribly pixelated.

Are there any parameters/config values I can tweak?

Cheers.

**Comment by simonfrost** [comment]
My implementation is playing the embedded stream as a background. On further searching, this looks like it might be a limitation of mobile devices... It'd be interesting to hear this confirmed though :-)

**Comment by stamat** [comment]
@simonfrost hey bud, late aren't I... Just went to buy a pack of cigarettes 😆 

Anyway yeah... https://developers.google.com/youtube/iframe_api_reference#october-24,-2019 Youtube dictates the quality of the stream depending on the conditions, like the device, internet speed and viewport size, they do this cause servers and their maintainance isn't free, and what we do here we use their service for free without the ads - so they don't like it, it spends their moneys.

I wonder how long till they force ads on embeds?! 😱 

Cheers! 🥂
