### ISSUE TITLE
feature: youtube-nocookie.com/embed/....

### ISSUE THREAD

**Issue by DejanS** [stamat/youtube-background#49]
change "link" in code youtube-background.js > line 144

144 > `let src = "https://www.youtube.com/embed/....`
to 
144 > `let src = "https://www.youtube-nocookie.com/embed/....`

**Comment by stamat** [comment]
Smart, didn't know about this! I'll add this as an option!

Hvala buraz!

**Comment by stamat** [comment]
@DejanS included in **v1.0.18** ✨ Thanks again!
