### ISSUE TITLE
Preview: file maxresdefault.jpg missing for some videos

### ISSUE THREAD

**Issue by franrodriguez123** [stamat/youtube-background#50]
Some videos don't have a maxresdefault.jpg and the preview is missing

This video don't have the maxresdefault.jpg image:
[maxresdefault](https://img.youtube.com/vi/JmIZb859q_o/maxresdefault.jpg)

However, hqdefault.jpg image is available
https://img.youtube.com/vi/JmIZb859q_o/hqdefault.jpg

**Comment by stamat** [comment]
@franrodriguez123 bud, sorry for the wait, this is resolved in **v1.0.19** Cheers 🥂
