### ISSUE TITLE
Issues with non-jquery working

### ISSUE THREAD

**Issue by todd-kruger** [stamat/youtube-background#54]
First, thank you so much for making this public.  

I tried to recreate your demo with non-jquery but it is not working.  Please see codepen https://codepen.io/tkruger/pen/poQGWNW

I used new VideoBackgrounds('[data-vbg]');   to call the script.

Any help would greatly be appreciated!  Or if you could post a demo without jQuery (and font awesome if possible) that would rock.  Trying to avoid large JS libraries when creating features for a website.

**Comment by somesang** [comment]
Replace the`data-youtube` attribute with `data-vbg` and it will work.

**Comment by stamat** [comment]
Ah, sorry for the late replies, I've been quite busy @Xeno4j . In the pen you've sent the HTML is

```html
<div id="ytbg" data-ytbg-fade-in="true" data-youtube="https://www.youtube.com/watch?v=eEpEeyqGlxA"></div>
```

As you can see there is no `[data-vbg]` attribute, but a `[data-youtube]` attribute, and changing to `[data-youtube]` will make the script work.
