### ISSUE TITLE
youtube-background | Video stop on mobile when switching tabs/ windows

### ISSUE THREAD

**Issue by steve-s-eightball-media** [stamat/youtube-background#57]
Hi developers,

I discovered this issue when I tested it on a simulator(Inspect tool on Chrome browser) and a mobile device (iPhone 12, Chrome).

The video played automatically on a mobile device, but when I switched between tabs, it stopped. Following is the jQuery I put in,

`jQuery('[data-vbg]').youtube_background({
	'lazyloading': true,
	'always-play' : true,
	'mobile' : true,
         'loop' : true
});`

Just wonder if anyone experienced the same issue.

Thank you,

**Comment by stamat** [comment]
@steve-s-eightball-media I see what you mean! You are right it is a bug. I'll look into it!

This happens not only on Chrome but on Safari to!

Thank you for reporting this! 🙌

**Comment by steve-s-eightball-media** [comment]
@stamat ,

Thank you and much appreciated.

**Comment by stamat** [comment]
@steve-s-eightball-media hey! The update is in the version **1.1.2**! Works for YouTube and regular Video backgrounds, butthere are issues with Vimeo, and it's probably not due this code, but it's due their player or their streams...

🙌

**Comment by steve-s-eightball-media** [comment]
Hi @stamat the issue is fixed on my end, thank you.

**Comment by stamat** [comment]
@steve-s-eightball-media thanks for confirming! ☺️
