### ISSUE TITLE
Yarn install fail on Windows after 1.0.15

### ISSUE THREAD

**Issue by asika32764** [stamat/youtube-background#59]
It can successfully install for 1.0.14 but failed after 1.0.15 and upper.

Error message:

> error https://registry.yarnpkg.com/youtube-background/-/youtube-background-1.0.15.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or direct
ory, open"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I assume that is the emoji file name break Windows path, since this project start using POOPS after 1.0.15.

See compare: https://github.com/stamat/youtube-background/compare/1.0.14...v1.0.15#diff-7134ec4840db4910869cf3cd4ad97314bc0c615a2d11a0ef9b7d0b2ea6be7cef

Yarn: v1.22.17
Windows: 10
Node: 16

**Comment by stamat** [comment]
@asika32764 hey there! Happy New Year! ✨

You are absolutely right. Thanks for catching this! I'm not using Windows so I would never see this issue!

I've resolved it in v1.1.3

Cheers!
