### ISSUE TITLE
Youtube title, share and add to watch later overlay appears for a brief moment

### ISSUE THREAD

**Issue by sylven** [stamat/youtube-background#6]
First thank you for making this!

I saw you have 'Add another wrapper so video can fade in when loaded' in the todo list, which might fix this issue.
Is there anyway to make the video load a bit later or hide it so it doesn't appear?

Thank you!

**Comment by stamat** [comment]
Hey, glad this piece of code is useful to you! Thanks for the idea, I'll add timed fade in option, or just fade it in when it starts playing when I have a moment to spare! Stay tuned!

**Comment by stamat** [comment]
@sylven yo dude, take a look at the latest release, it fixes your problem! 🎉 Stay safe!
