### ISSUE TITLE
The poster parameter is not working

### ISSUE THREAD

**Issue by Sentinel-7** [stamat/youtube-background#60]
My own picture doesn't work
data-vbg-poster="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg"
The script uploads its own picture from YouTube

**Comment by stamat** [comment]
@Sentinel-7 Hey man, thanks for catching this! Happy new year! ✨ 

I've forgot to add `url()` for the link this is why it wasn't working. It has been resolved in v1.1.3!

Cheers!
