### ISSUE TITLE
Lighthouse tests complain that iframe does not have a title .

### ISSUE THREAD

**Issue by Aduffy** [stamat/youtube-background#62]
Lighthouse tests complain that iframe does not have a title .

I added playerElement.setAttribute("title", "Video Player");  in my copy to resolve.

**Comment by stamat** [comment]
@Aduffy nice catch! I'll add titles! Thank you for reporting! ❤️

**Comment by stamat** [comment]
@Aduffy the update is available in the version **1.1.6** ✨  If you are using this as a background, consider adding `aria-hidden="true"` to the background container. This too will solve your issue.
