### ISSUE TITLE
Playing private Vimeo videos

### ISSUE THREAD

**Issue by a-am** [stamat/youtube-background#64]
For unlisted Vimeo videos is there a way to append the `h=xxxxxxx` param to the url so that the video can play? It appears to be removed when initiated.

**Comment by stamat** [comment]
@a-am hey thanks for letting me know about this! I'll add it in the next version!

If it is possible can you share how the link looks like? Or maybe the full private video link! It would help, so I don't log in to vimeo an upload a private video.

**Comment by a-am** [comment]
@stamat here is the Vimeo documentation link to what I am referring to: https://help.vimeo.com/hc/en-us/articles/12426470858001-Embedded-player-displays-This-video-does-not-exist-message

**Comment by stamat** [comment]
@a-am great, this helps a ton! Thank you!

**Comment by stamat** [comment]
@a-am the update is available in the version **1.1.6** ✨

You can use any of these three notations for the `data-vbg` attrubute value:

https://vimeo.com/304887422/34c51f7a09

https://vimeo.com/304887422:34c51f7a09

https://vimeo.com/304887422?h=34c51f7a09

Hope this helps!
